### ISSUE TITLE
Checklist for workshop organisation

### ISSUE THREAD

**Issue by pherterich** [betatim/build-a-binder#7]
My start on a list of things to do

- [ ] book room
- [ ] book catering
- [ ] send out instructions on how to get to the location
- [ ] wifi (if not eduroam/ additional guest options)
- [ ] recording?
- [ ] organise for vegetarian, gluten free, and tasty food (can we take care of 95% of food allergies/choices with one meal?)
 - [ ] email participants about the food options we have/ ask for dietary requirements upon registration
- [ ] Code of Conduct
- [ ] sufficient electricity access points
- [ ] spare adaptors (chargers, screen connectors)

On the day
- [ ] arrange room 
- [ ] sign post building

**Comment by RaoOfPhysics** [comment]
Non-academics won't have eduroam, so good to have a few wifi options!

**Comment by pherterich** [comment]
Done. Ashamed how the vegan could forget to spell out the food requirements that need organising...

**Comment by trallard** [comment]
- [ ] Code of conduct

**Comment by betatim** [comment]
MY COC suggestion: https://mozillafestival.org/guidelines

**Comment by betatim** [comment]
How much effort do you think organising for a recording of the event will be?

**Comment by pherterich** [comment]
Depends on the location I'd say. At Birmingham, we could use the lecture capture system for everything that's a standard presentation/demo. I might need to fiddle around a bit to get that into a video file that you could upload to various free platforms, but basic recording and a link to our system isn't too complicated, so we could give that a shot and see if people find it useful.

**Comment by RaoOfPhysics** [comment]
Pinging @npscience for general wisdom and for her experience with the recently concluded \#eLifeSprint she ran.

**Comment by heluc** [comment]
I booked the room for the Lausanne event at EPFL, should be big enough for 30 people, can be arranged for teaching and workshop format

**Comment by RaoOfPhysics** [comment]
Also check out this post on the UK Government's Accessibility blog: [Advice for making events and presentations accessible](https://accessibility.blog.gov.uk/2018/03/13/advice-for-making-events-and-presentations-accessible/)

**Comment by betatim** [comment]
Added the checklist items to the top comment.

My personal opinion is -0 on recording of any form. It is a lot of work to get a good recording, and even good recordings are not soo useful if the format isn't a talk/presentation. At least I very rarely watch one and think "yeah that was worth my time". I'd rather invest effort in making sure there is good audio for everyone in the room. (Recording the event also makes it impossible to have Chatham House Rule, which seems to encourage people to say things.)

Legalese COC:  I think the full version of the MozFest guidelines (https://www.mozilla.org/en-US/about/governance/policies/participation/) linked from the original link is what you are looking for? The important modification would be to name two people (with at least one unconnected to those organising the event) as points of contact. Note: because of who I am I have very little experience with COC related issues, so I defer to those who want to champion a particular approach, especially if that is different from what I suggest.
